@Host = https://localhost:7001

GET {{Host}}/

###
GET {{Host}}/documents

###
GET {{Host}}/documents/2f3357b8-00a9-44f4-b9cd-a9818d80e0b8


POST {{Host}}/documents
Content-Type: application/json

{
  "title": "Layered Architecture Notes",
  "rawText": "Layered architecture is one of the most common patterns in enterprise systems.\n\nIt organizes code into layers, usually presentation, application, domain, and infrastructure.\n\nA major downside is that changes may need to cross many layers, which can slow delivery.",
  "sourceType": "Book",
  "author": "Practice Notes"
}

###

POST {{Host}}/documents
Content-Type: application/json

{
  "title": "",
  "rawText": "short",
  "sourceType": "Book"
}
